### ISSUE TITLE
Does not correctly handle cases where node.offsetParent != document.body

### ISSUE THREAD

**Issue by rjgotten** [jeremenichelli/hunt#1]
The `updateMetrics` method explicitly relies on the `node.offsetTop` property. This value is relative to the offset parent, which is the closest element that is positioned non-statically, i.e. , has a relative; absolute; or fixed position. This does not need to be the body element that corresponds to the master scroll container.

Scrap what you're doing now and use `getBoundingClientRect` (which is well-supported just about everywhere). Get coordinates directly in window/viewport space!

It saves you the hassle of manually mucking about with nested offsetParents **and** saves you the effort of dealing with the page scroll offset to map document-space coordinates to window-/viewport-space coordinates and vice versa, including the headaches of reliable cross-browser scroll offset calculation.

**Comment by jeremenichelli** [comment]
You're totally right. Actually, I already have the solution using `getBoundingClientRect` from day one, but it triggered way more re-paint than this one.

I'm running some tests and trying to figure out the best way to include it and don't affect performance, but a `getBoundingClientRect` approach will be in the next version for sure.

**Comment by rjgotten** [comment]
> I'm running some tests and trying to figure out the best way to include it and don't affect performance

Batching `getBoundingClientRect` calls with an animation frame should perform best.

(Also: don't forget that you need to check the length of `getClientRects` before calling getBCR! Detached nodes in IE don't play nice with getBCR!)

**Comment by jeremenichelli** [comment]
Nice. Is that an *IE8* issue? Because my intention is to support *IE9+*.

**Comment by rjgotten** [comment]
> Nice. Is that an IE8 issue? Because my intention is to support IE9+.

Up to and including IE 11, but fixed in Edge.

**Comment by jeremenichelli** [comment]
@rjgotten I've published a branch with `clientBoundingRect` approach applied and debounce during scroll if you want to check it out https://github.com/jeremenichelli/hunt/tree/debounce-client-rect

**Comment by jeremenichelli** [comment]
Still not merging it because I'm seeing that it's taking a lot of processing time while scrolling, so any suggestions are welcomed :grinning:

**Comment by YohannParis** [comment]
I had the same problem and wasn't understanding the issue. I try `getBoundingClientRect` and it is indeed heavy on the CPU, specially for mobile.

I made a small while loop to find the top node parent. Works well for me because I nodes aren't deep.

```js
// assign or updates instance metrics
Hunted.prototype.updateMetrics = function() {
	this.height = this.element.clientHeight;
	this.top = 0;

	// try to find each parent is at the top of the viewport
	var topElement = this.element.parentNode;
	while(topElement.offsetTop != 0){

		// add the parent offseTop
		this.top += topElement.offsetTop;

		// check the grand-parent
		topElement = topElement.parentNode;
	}

	// Add the element offsetTop
	this.top += this.element.offsetTop;
}; 
```

**Comment by jeremenichelli** [comment]
That's actually a really nice solution @YohannParis. The next step would be to test a case where you have a bunch of nested elements with `position: relative` and see how much this `offsetTop` acummulation costs in scripting.

**Comment by rjgotten** [comment]
> That's actually a really nice solution

Please do note that the `offsetTop` property does not take into account shifts caused by CSS transformations, which is something that `getBoundingClientRect` *does* do.

> Still not merging it because I'm seeing that it's taking a lot of processing time while scrolling, so any suggestions are welcomed

Did you profile the code and traced the source of the processing time down to the calls to `getBoundingClientRect`, or did you just assume it was to blame? I'm asking because DOM libraries like jQuery use `getBoundingClientRect` where available **specifically** because it is significantly more performant than manually walking the DOM tree up and aggregating the offset properties.

**Comment by jeremenichelli** [comment]
I did trace it @rjgotten. It was a couple of weeks ago so I can't post a frame and time screenshots, but I promise to take a further look at it tomorrow and came back with it.

**Comment by rjgotten** [comment]
One possible general optimization that comes to mind; don't recheck on every animation frame. Smear out the computations for your hunted elements over multiple frames. Realistically, a user isn't going to notice if you're off by 5 or 10 pixels, after all.

**Comment by jeremenichelli** [comment]
@rjgotten made another commit to the special branch, run metrics and saw similar metrics to the ones present in `master`, if you can download that branch and take a look. I'm about to create a new example with multiple elements to "hunt" and get more meaningful results.

**Comment by rjgotten** [comment]
One more thing that comes to mind:
the current code loops over elements to call `getBoundingClientRect`; run checks against the bounding rectangle; and then conditionally run the `in` or `out` callback. 

Those callbacks run synchronously in each individual iteration of the loop. If they perform any kind of DOM write, that means you are extremely likely to land in a situation where layout thrashing will occur. In order to avoid that, push the `in` and `out` candidates that pass the checks onto temporary arrays and flush them out *after* the loop and all the read operations have finished.

**Comment by jeremenichelli** [comment]
I think that would really tricky. With requestAnimationFrame debouncing we are already not entering the loop if there's an activity on going the current frame, and later you'll need another for loop for all the queued functions.

**Comment by jeremenichelli** [comment]
@rjgotten added to this feature branch a **test.html** page, if you have some time compare it with the branch version and the master version (you'll have to change the script `src` manually) and you'll see that `getClientBoundingRect` triggers more **repaint** and increase the scripting time since in the offsetApproach you're just consulting previously stored properties.

The new plan is to create a new branch, adding `requestAnimationFrame` debounce and @YohannParis approach in case the element's `offsetParent` is not `body`.

**Comment by jeremenichelli** [comment]
Stress test run using `getClientBoundingRect`
![getClientBoundingRect](https://cloud.githubusercontent.com/assets/3856481/13969788/a10417ee-f063-11e5-8487-131da03c2b38.png)

Stress test run using `offsetTop` with parent offset checking
![captura de pantalla 2016-03-22 a las 7 22 34 p m](https://cloud.githubusercontent.com/assets/3856481/13969851/e8bf10de-f063-11e5-8aac-327dbb769926.png)

As you can see @rjgotten, though numbers are close, the scripting time is way higher with `getClientBoundingRect` during scrolling time. I repeat this several times, and with little less or more differences, at least on the numbers using `offsetTop` used less **CPU**. Painting and rendering was slightly better too, but nothing the eye can really notice.

**Comment by rjgotten** [comment]
@jeremenichelli 

Your performance test is bogus. You are muddying waters by including CSS transitions running over time and you are artificially inflating paint times by setting a CSS transform and will-change hint on each individual element, which promotes each individual element to its own compositing layer and royally messes with the paint times.

Here's what that test looks like with the wil-chang hint, transform and transition ripped out and replaced with a simple visibility visible/hidden switch replacing it and with the hunt library updated to batch the `getBoundingClientRect` reads in an isolated read pass and the `in` and `out` callback execution into a second separate pass:

![timeline](https://cloud.githubusercontent.com/assets/442808/13982547/093b03fe-f0eb-11e5-92e2-5bfb920aee07.png)



Better, yes?
Want a pull request?

**Comment by jeremenichelli** [comment]
Regarding the tests, you're right I'm forcing the browser to create a new composite layer. Of course these was on purpose because it's more probable that developers will use this library to apply a change that will trigger that rather than just adding a `visibility: hidden`.

But it's a valid note, I will re run my tests doing just that minor change and see which brenchmarks are better.

Feel free to create oull request, code is always welcome, it's always better.

**Comment by jeremenichelli** [comment]
Run tests on both approaches just toggling `visibility` property:

### getBoundingClientRect
![captura de pantalla 2016-03-23 a las 5 01 46 p m](https://cloud.githubusercontent.com/assets/3856481/13999033/15f2a3bc-f119-11e5-8366-0535364c2a64.png)

### offsetTop
![captura de pantalla 2016-03-23 a las 5 01 28 p m](https://cloud.githubusercontent.com/assets/3856481/13999044/2441fb48-f119-11e5-8c80-c37bfe471e98.png)

Still seeing better numbers using `offset`.

**Comment by rjgotten** [comment]
Frame bars are smaller because you're getting a lot of forced reflows in the getBCR version -- Note the red markings on top of the rendering bars... -- , which is something that I solved in my patch.

I'll create a pull request. I'd be very interested in what it shows on your machine.

**Comment by jeremenichelli** [comment]
I've downloaded your repo. I'm really impress by the number you got using `getBoundingClientRect` which is indeed a heavy scripting task, but at least here in the best cases the approach equals the performance and frames of using `offset`. In general I still see the double of scripting time.

It's good to mention that your approach using `getBoundingClientRect` is way better than mine.

Here are the metrics I got...


### getBoundingClientRect 
![captura de pantalla 2016-03-24 a las 12 27 54 p m](https://cloud.githubusercontent.com/assets/3856481/14022495/d79fc5e4-f1be-11e5-935a-2414856ba18a.png)


### offset
![captura de pantalla 2016-03-24 a las 12 28 16 p m](https://cloud.githubusercontent.com/assets/3856481/14022497/db81ca36-f1be-11e5-9e20-038c7cc9af7a.png)

**Comment by jeremenichelli** [comment]
On a side note, this issue is about the script having problems when the parent of the element you're *hunting* has a `position: relative`, that bug is ready to be solved and this issue has already turned into a paint, frame and performance report. We should either rename it or close it later.

**Comment by rjgotten** [comment]
Yeah, it should probably be split into multiple issues for future sanity. :)

**Comment by jeremenichelli** [comment]
I'm closing this issue since the problem rose in the title has been fixed in last release.
